import { Container, Link, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "react-loading-skeleton/dist/skeleton.css";
import AuthProvider from "./auth/provider";
import "./globals.css";
import NavBar from "./NavBar";
import QueryClientProvider from "./QueryClientProvider";
import "./theme-config.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme accentColor="iris" radius="large">
              <div className="flex flex-col">
                <div className="justify-start">
                  <NavBar />
                  <main className="p-5">
                    <Container>{children}</Container>
                  </main>
                </div>
                <footer className="text-center p-5 lg:mt-[10vh]">
                  Made By <Link href="https://github.com/b14ck0ps">Azran</Link>
                </footer>
              </div>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
